Repository ltb-project/self-service-password, pull requests merged in 2020-08, with the labels that each got.

#406 Move inline javascript to its own file fixes (#404)
  index.php
  js/self-service-password.js
Labels: enhancement

#407 Upgrade jquery to 3.5.1
  index.php
  js/jquery-3.3.1.min.js
  js/jquery-3.5.1.min.js
Labels: enhancement

#372 Use Smarty framework
  conf/config.inc.php
  css/font-awesome.min.css
  css/self-service-password.css
  htdocs/change.php
  htdocs/changesshkey.php
  htdocs/css/self-service-password.css
  htdocs/images/favicon.ico
  htdocs/images/ltb-logo.png
  htdocs/images/unsplash-clouds.jpeg
  htdocs/images/unsplash-sky.jpeg
  htdocs/images/unsplash-space.jpeg
  htdocs/images/unsplash-stars.jpeg
  htdocs/index.php
  htdocs/js/self-service-password.js
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  htdocs/sendsms.php
  htdocs/sendtoken.php
  htdocs/setquestions.php
  htdocs/vendor/bootstrap/css/bootstrap-theme.css.map
  htdocs/vendor/bootstrap/css/bootstrap-theme.min.css
  htdocs/vendor/bootstrap/css/bootstrap.css.map
  htdocs/vendor/bootstrap/css/bootstrap.min.css
  htdocs/vendor/bootstrap/fonts/glyphicons-halflings-regular.eot
  htdocs/vendor/bootstrap/fonts/glyphicons-halflings-regular.svg
  htdocs/vendor/bootstrap/fonts/glyphicons-halflings-regular.ttf
  htdocs/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff
  htdocs/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff2
  htdocs/vendor/bootstrap/js/bootstrap.min.js
  htdocs/vendor/font-awesome/css/font-awesome.min.css
  htdocs/vendor/font-awesome/fonts/FontAwesome.otf
  htdocs/vendor/font-awesome/fonts/fontawesome-webfont.eot
  htdocs/vendor/font-awesome/fonts/fontawesome-webfont.svg
  htdocs/vendor/font-awesome/fonts/fontawesome-webfont.ttf
  htdocs/vendor/font-awesome/fonts/fontawesome-webfont.woff
  htdocs/vendor/font-awesome/fonts/fontawesome-webfont.woff2
  htdocs/vendor/jquery/js/jquery-3.5.1.min.js
  htdocs/vendor/jquery/js/jquery-3.5.1.min.map
  index.php
  menu.php
  pages/resetbytoken.php
  templates/change.tpl
  templates/changesshkey.tpl
  templates/footer.tpl
  templates/header.tpl
  templates/index.tpl
  templates/menu.tpl
  templates/policy.tpl
  templates/resetbyquestions.tpl
  templates/resetbytoken.tpl
  templates/sendsms.tpl
  templates/sendtoken.tpl
  templates/setquestions.tpl
  templates_c/remove.txt
Labels: enhancement

#332 Docker file
  .dockerignore
  Dockerfile
Labels: enhancement

#409 LDAP exop password modify
  conf/config.inc.php
  htdocs/change.php
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  lib/functions.inc.php
Labels: enhancement

#157 Using ldap_exop_passwd if available (PHP>=7.2)
  lib/functions.inc.php
Labels: enhancement

#410 More work on smarty migration
  htdocs/index.php
  templates/index.tpl
Labels: enhancement

#411 Allowing Email as URL-Parameter
  htdocs/index.php
  htdocs/sendtoken.php
  lang/ca.inc.php
  lang/cn.inc.php
  lang/cs.inc.php
  lang/de.inc.php
  lang/ee.inc.php
  lang/el.inc.php
  lang/en.inc.php
  lang/es.inc.php
  lang/eu.inc.php
  lang/fr.inc.php
  lang/hu.inc.php
  lang/it.inc.php
  lang/ja.inc.php
  lang/nb-NO.inc.php
  lang/nl.inc.php
  lang/pl.inc.php
  lang/pt-BR.inc.php
  lang/pt-PT.inc.php
  lang/ru.inc.php
  lang/sk.inc.php
  lang/sl.inc.php
  lang/sv.inc.php
  lang/tr.inc.php
  lang/uk.inc.php
  lang/zh-CN.inc.php
  lang/zh-TW.inc.php
  lib/functions.inc.php
  templates/sendtoken.tpl
Labels: enhancement

#301 New policy: Forbidden ldap fields
  conf/config.inc.php
  htdocs/change.php
  htdocs/index.php
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  lang/ca.inc.php
  lang/cn.inc.php
  lang/cs.inc.php
  lang/de.inc.php
  lang/ee.inc.php
  lang/el.inc.php
  lang/en.inc.php
  lang/es.inc.php
  lang/fr.inc.php
  lang/hu.inc.php
  lang/it.inc.php
  lang/ja.inc.php
  lang/nb-NO.inc.php
  lang/nl.inc.php
  lang/pl.inc.php
  lang/pt-BR.inc.php
  lang/pt-PT.inc.php
  lang/ru.inc.php
  lang/sk.inc.php
  lang/sl.inc.php
  lang/sv.inc.php
  lang/tr.inc.php
  lang/uk.inc.php
  lang/zh-CN.inc.php
  lang/zh-TW.inc.php
  lib/functions.inc.php
  tests/CheckPasswordTest.php
Labels: enhancement

#413 Update Polish localization
  lang/pl.inc.php
Labels: translation

#415 Fixes units tests
  Dockerfile
  lang/eu.inc.php
  lang/pl.inc.php
  tests/CheckPasswordTest.php
Labels: bug

#416 Prehook - ltb-project/self-service-password#220
  conf/config.inc.php
  docs/config_preposthook.rst
  docs/index.rst
  htdocs/change.php
  htdocs/index.php
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  lib/functions.inc.php
  templates/change.tpl
  templates/resetbyquestions.tpl
  templates/resetbytoken.tpl
  tests/HookTest.php
  tests/PostHookTest.php
Labels: enhancement
