Repository ltb-project/self-service-password, pull requests merged in 2021-04, with the labels that each got.

#491 do not override config.inc.local.php vars
  conf/config.inc.php
Labels: enhancement

#469 docs(docker)
  Dockerfile
  docs/installation.rst
  packaging/README
  packaging/docker/Dockerfile
Labels: enhancement

#225 rate-limiting with json files
  conf/config.inc.php
  docs/config_general.rst
  htdocs/index.php
  htdocs/sendsms.php
  htdocs/sendtoken.php
  lang/ca.inc.php
  lang/cn.inc.php
  lang/cs.inc.php
  lang/de.inc.php
  lang/ee.inc.php
  lang/el.inc.php
  lang/en.inc.php
  lang/es.inc.php
  lang/eu.inc.php
  lang/fr.inc.php
  lang/hu.inc.php
  lang/it.inc.php
  lang/ja.inc.php
  lang/nb-NO.inc.php
  lang/nl.inc.php
  lang/pl.inc.php
  lang/pt-BR.inc.php
  lang/pt-PT.inc.php
  lang/rs.inc.php
  lang/ru.inc.php
  lang/sk.inc.php
  lang/sl.inc.php
  lang/sv.inc.php
  lang/tr.inc.php
  lang/uk.inc.php
  lang/zh-CN.inc.php
  lang/zh-TW.inc.php
  lib/functions.inc.php
Labels: enhancement

#224 SMS OVH provider
  docs/config_sms.rst
  docs/sms_api.rst
  htdocs/sendsms.php
  lib/smsovh/composer.json
  lib/smsovh/smsapi-ovh.inc.php
Labels: enhancement

#501 Remove extra semicolon from setquestions template
  templates/setquestions.tpl
Labels: bug

#505 fix(captcha): missing gd library
  packaging/docker/Dockerfile
Labels: bug, packaging

#508 fix(undefined)
  htdocs/index.php
Labels: enhancement

#507 fix(reset)
  lib/functions.inc.php
  tests/CheckPasswordTest.php
Labels: bug
