Repository ltb-project/self-service-password, pull requests merged in 2021-05, with the labels that each got.

#510 feat(ssh): public key check ( #509 )
  conf/config.inc.php
  htdocs/change.php
  htdocs/changesshkey.php
  htdocs/index.php
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  htdocs/sendsms.php
  lang/ca.inc.php
  lang/cn.inc.php
  lang/cs.inc.php
  lang/de.inc.php
  lang/ee.inc.php
  lang/el.inc.php
  lang/en.inc.php
  lang/es.inc.php
  lang/eu.inc.php
  lang/fr.inc.php
  lang/hu.inc.php
  lang/it.inc.php
  lang/ja.inc.php
  lang/nb-NO.inc.php
  lang/nl.inc.php
  lang/pl.inc.php
  lang/pt-BR.inc.php
  lang/pt-PT.inc.php
  lang/rs.inc.php
  lang/ru.inc.php
  lang/sk.inc.php
  lang/sl.inc.php
  lang/sv.inc.php
  lang/tr.inc.php
  lang/uk.inc.php
  lang/zh-CN.inc.php
  lang/zh-TW.inc.php
  lib/detectbrowserlanguage.php
  lib/functions.inc.php
  lib/smsovh/smsapi-ovh.inc.php
  tests/CheckPasswordTest.php
  tests/CheckSshkeyTest.php
  tests/HookTest.php
  tests/LangTest.php
Labels: enhancement

#512 docs(sshkey)
  docs/config_sshkey.rst
  docs/index.rst
Labels: documentation

#517 fix(mail): add sendmail to Docker image
  packaging/docker/Dockerfile
Labels: enhancement

#515 docs(multi-tenancy): adds samples setting multi-tenancy header
  docs/config_general.rst
Labels: documentation

#521 If token was provided by SMS, check initial SMS code before changing password
  htdocs/resetbytoken.php
  htdocs/sendsms.php
Labels: bug, security

#522 [Security:low] Dismiss captcha once it is used
  htdocs/change.php
  htdocs/changesshkey.php
  htdocs/resetbyquestions.php
  htdocs/sendsms.php
  htdocs/sendtoken.php
  htdocs/setquestions.php
Labels: bug, security

#529 Typo in resetbytoken resulting in mails not being sent
  htdocs/resetbytoken.php
Labels: bug

#536 adding Kerberos authentication support
  conf/config.inc.php
  docs/config_ldap.rst
  htdocs/change.php
Labels: enhancement
