Repository ltb-project/self-service-password, pull requests merged in 2021-03, with the labels that each got.

#471 Added Serbian language
  lang/rs.inc.php
Labels: translation

#475 Option for ppolicy control
  conf/config.inc.php
  docs/config_ldap.rst
  htdocs/change.php
  htdocs/index.php
  lang/ca.inc.php
  lang/cn.inc.php
  lang/cs.inc.php
  lang/de.inc.php
  lang/ee.inc.php
  lang/el.inc.php
  lang/en.inc.php
  lang/es.inc.php
  lang/eu.inc.php
  lang/fr.inc.php
  lang/hu.inc.php
  lang/it.inc.php
  lang/ja.inc.php
  lang/nb-NO.inc.php
  lang/nl.inc.php
  lang/pl.inc.php
  lang/pt-BR.inc.php
  lang/pt-PT.inc.php
  lang/rs.inc.php
  lang/ru.inc.php
  lang/sk.inc.php
  lang/sl.inc.php
  lang/sv.inc.php
  lang/tr.inc.php
  lang/uk.inc.php
  lang/zh-CN.inc.php
  lang/zh-TW.inc.php
  lib/functions.inc.php
Labels: enhancement

#477 docs(keyphrase): update comments/docs, when should keyphrase be set
  conf/config.inc.php
  docs/config_sms.rst
Labels: documentation

#476 fix(lang): re-include allowed_lang check
  htdocs/index.php
Labels: bug

#479 Update Serbian translation
  lang/rs.inc.php
Labels: translation
