Repository ltb-project/self-service-password, pull requests merged in 2021-06, with the labels that each got.

#530 Change expired password as manager
  docs/config_ldap.rst
  htdocs/change.php
  rest/v1/adminchangepassword.php
  rest/v1/changepassword.php
  scripts/multi_ldap_change.php
Labels: enhancement

#539 fix(version): mismatch between htdocs/index.php and rest/v1/include.php
  rest/v1/include.php
Labels: enhancement

#541 core(update): apache 2.4.46
  packaging/docker/Dockerfile
Labels: security

#542 fix(notify): don't send notification if modification failed
  htdocs/changesshkey.php
Labels: bug

#545 docs(ratelimit): typo
  docs/config_general.rst
Labels: documentation

#546 feat(mails): using several mail attributes
  conf/config.inc.php
  docs/config_mail.rst
  htdocs/change.php
  htdocs/changesshkey.php
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  htdocs/sendtoken.php
  rest/v1/adminchangepassword.php
  rest/v1/changepassword.php
Labels: enhancement

#513 fix(sshkeys): don't send mail notification when entry was not changed
  htdocs/changesshkey.php
Labels: bug

#547 Update de.inc.php
  lang/de.inc.php
Labels: translation

#551 fix(docs): invalid nginx root serving ssp
  docs/config_nginx.rst
Labels: documentation

#549 Added sms api for signal-cli
  docs/sms_api.rst
  lib/smsapi-signal-cli.inc.php
Labels: enhancement

#558 fix(docs): ratelimit check interval should be 1h, not 1min
  docs/config_general.rst
Labels: documentation

#562 Document $allowed_lang var
  docs/config_general.rst
Labels: documentation

#564 Updated IT translation
  lang/it.inc.php
Labels: translation
