Repository ltb-project/self-service-password, pull requests merged in 2022-09, with the labels that each got.

#708 Get entry in checkpassword REST service
  docs/webservices.rst
  rest/v1/checkpassword.php
Labels: enhancement

#712 Catch user not found error
  htdocs/changesshkey.php
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  htdocs/sendtoken.php
  htdocs/setquestions.php
Labels: bug

#718 Update config_apache.rst
  docs/config_apache.rst
Labels: documentation
