Repository ltb-project/self-service-password, pull requests merged in 2022-07, with the labels that each got.

#673 feat(sms): Allow more than one mobile attribute #658
  conf/config.inc.php
  docs/config_sms.rst
  htdocs/sendsms.php
  lib/LtbAttributeValue_class.php
Labels: enhancement

#675 Feat mail factorize attributes
  htdocs/change.php
  htdocs/changesshkey.php
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  lib/LtbAttributeValue_class.php
  rest/v1/adminchangepassword.php
  rest/v1/changepassword.php
Labels: enhancement

#669 Update TR translation
  lang/tr.inc.php
Labels: translation

#514 fix(sshkey): should add one sshPublicKey per key
  lib/functions.inc.php
Labels: enhancement

#676 Remove warning "Decoding error"
  htdocs/sendtoken.php
  lib/LtbAttributeValue_class.php
Labels: enhancement

#592 Fix 563
  templates/change.tpl
Labels: bug

#685 hide failure by default for mailnomatch issue #610
  conf/config.inc.php
Labels: security

#686 fix check password toward ldap attribute for token based methods issu…
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  lib/functions.inc.php
  tests/CheckPasswordTest.php
Labels: bug
