Repository ltb-project/self-service-password, pull requests merged in 2022-08, with the labels that each got.

#680 captcha use dedicated session cookie fix #602
  htdocs/captcha.php
  htdocs/change.php
  htdocs/changesshkey.php
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  htdocs/sendsms.php
  htdocs/sendtoken.php
  htdocs/setquestions.php
  lib/captcha.inc.php
Labels: bug

#683 Rate limit optional support per ip (ratelimit_filter_by_ip)
  conf/config.inc.php
  docs/config_general.rst
  docs/config_rate_limit.rst
  docs/index.rst
  htdocs/index.php
  lib/functions.inc.php
Labels: enhancement

#696 Improve documentation, parse php code
  docs/conf.py
  docs/config_apache.rst
  docs/config_general.rst
  docs/config_ldap.rst
  docs/config_mail.rst
  docs/config_nginx.rst
  docs/config_ppolicy.rst
  docs/config_preposthook.rst
  docs/config_questions.rst
  docs/config_rate_limit.rst
  docs/config_sms.rst
  docs/config_sshkey.rst
  docs/config_tokens.rst
  docs/sms_api.rst
  docs/webservices.rst
Labels: documentation

#688 Fix password check ldap
  lib/functions.inc.php
  rest/v1/checkpassword.php
Labels: bug

#702 Use require nonce for file inclusion
  conf/config.inc.php
  docs/config_general.rst
Labels: enhancement

#703 Fix reset by questions display after password change
  templates/resetbyquestions.tpl
Labels: bug

#699 Check parameters before calling hash_equals
  htdocs/resetbyquestions.php
Labels: bug
