Repository ltb-project/self-service-password, pull requests merged in 2023-11, with the labels that each got.

#815 Complete and fix pt-BR translation
  lang/pt-BR.inc.php
Labels: translation

#818 Do not trust SMS number from crypted token, search it again in LDAP Directory
  htdocs/sendsms.php
Labels: security

#774 Announce that the smarty3 package needs to be installed manually
  packaging/debian/NEWS
  packaging/debian/self-service-password.config
  packaging/debian/self-service-password.postinst
  packaging/debian/self-service-password.templates
Labels: packaging
