Repository ltb-project/self-service-password, pull requests merged in 2023-05, with the labels that each got.

#771 Restrict languages to php files
  htdocs/index.php
Labels: enhancement

#749 Prevent account disclosure in password reset by mail token page
  conf/config.inc.php
  docs/config_general.rst
  htdocs/sendtoken.php
  lang/ar.inc.php
  lang/ca.inc.php
  lang/cn.inc.php
  lang/cs.inc.php
  lang/de.inc.php
  lang/ee.inc.php
  lang/el.inc.php
  lang/en.inc.php
  lang/es.inc.php
  lang/eu.inc.php
  lang/fr.inc.php
  lang/hu.inc.php
  lang/it.inc.php
  lang/ja.inc.php
  lang/nb-NO.inc.php
  lang/nl.inc.php
  lang/pl.inc.php
  lang/pt-BR.inc.php
  lang/pt-PT.inc.php
  lang/rs.inc.php
  lang/ru.inc.php
  lang/sk.inc.php
  lang/sl.inc.php
  lang/sv.inc.php
  lang/tr.inc.php
  lang/uk.inc.php
  lang/zh-CN.inc.php
  lang/zh-TW.inc.php
Labels: enhancement, security

#775 Update tr.inc.php
  lang/tr.inc.php
Labels: translation

#777 Typo in config_tokens.rst
  docs/config_tokens.rst
Labels: documentation
