Repository ltb-project/self-service-password, pull requests merged in 2023-10, with the labels that each got.

#808 First implementation of a page to set mail and phone attributes
  conf/config.inc.php
  docs/config_sms.rst
  docs/config_tokens.rst
  docs/index.rst
  docs/set_attributes.rst
  htdocs/index.php
  htdocs/setattributes.php
  lang/ar.inc.php
  lang/ca.inc.php
  lang/cn.inc.php
  lang/cs.inc.php
  lang/de.inc.php
  lang/ee.inc.php
  lang/el.inc.php
  lang/en.inc.php
  lang/es.inc.php
  lang/eu.inc.php
  lang/fr.inc.php
  lang/hu.inc.php
  lang/it.inc.php
  lang/ja.inc.php
  lang/nb-NO.inc.php
  lang/nl.inc.php
  lang/pl.inc.php
  lang/pt-BR.inc.php
  lang/pt-PT.inc.php
  lang/rs.inc.php
  lang/ru.inc.php
  lang/sk.inc.php
  lang/sl.inc.php
  lang/sv.inc.php
  lang/tr.inc.php
  lang/uk.inc.php
  lang/zh-CN.inc.php
  lang/zh-TW.inc.php
  lib/functions.inc.php
  templates/sendsms.tpl
  templates/sendtoken.tpl
  templates/setattributes.tpl
Labels: enhancement, sponsor

#797 Use LTB LDAP common PHP lib
  .gitignore
  composer.json
  composer.lock
  htdocs/change.php
  htdocs/changesshkey.php
  htdocs/index.php
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  htdocs/sendsms.php
  htdocs/sendtoken.php
  htdocs/setattributes.php
  htdocs/setquestions.php
  lib/LtbAttributeValue_class.php
  packaging/docker/Dockerfile
  rest/v1/adminchangepassword.php
  rest/v1/changepassword.php
  rest/v1/checkpassword.php
  rest/v1/include.php
  scripts/encrypt_answers.php
  scripts/multi_ldap_change.php
Labels: enhancement, dependencies

#812 Update tr.inc.php
  lang/tr.inc.php
Labels: translation
