Repository ltb-project/self-service-password, pull requests merged in 2024-09, with the labels that each got.

#971 Only call ldap_get_dn on an entry
  scripts/multi_ldap_change.php
Labels: bug, sponsor

#974 Override all parameters with values from $secondaries_ldap
  scripts/multi_ldap_change.php
Labels: bug, sponsor

#967 use symfony cache for managing session-side storage (#954)
  composer.json
  conf/config.inc.php
  docs/config_general.rst
  docs/config_sms.rst
  docs/config_tokens.rst
  docs/upgrade.rst
  htdocs/index.php
  htdocs/resetbytoken.php
  htdocs/sendsms.php
  htdocs/sendtoken.php
  packaging/debian/control
  packaging/rpm/SPECS/self-service-password.spec
Labels: enhancement

#978 prevent sending sms twice + share cache functions in dedicated lib/cache.php (#763)
  htdocs/index.php
  htdocs/sendsms.php
  htdocs/sendtoken.php
  lib/cache.php
  templates/sendsms.tpl
Labels: bug

#980 use cache functions from ltb-common (#979)
  htdocs/index.php
  htdocs/resetbytoken.php
  htdocs/sendsms.php
  htdocs/sendtoken.php
  lib/cache.php
Labels: enhancement

#983 improve cache modularity (#982)
  conf/config.inc.php
  docs/config_general.rst
  docs/upgrade.rst
  htdocs/index.php
  packaging/debian/control
  packaging/rpm/SPECS/self-service-password.spec
Labels: enhancement

#989 Arabic language support in documentation
  docs/config_general.rst
  docs/images/ar.png
Labels: documentation

#988 Use page size parameter from ltb-common (#985)
  composer.json
  conf/config.inc.php
  docs/config_ldap.rst
  docs/upgrade.rst
  htdocs/index.php
Labels: enhancement

#990 update ltb-common library to v0.3.0 (#948)
  composer.json
Labels: packaging

#992 #943: Removed duplicated detect language code.
  htdocs/index.php
  lib/detectbrowserlanguage.php
Labels: enhancement
