Repository ltb-project/self-service-password, pull requests merged in 2024-03, with the labels that each got.

#845 prevent multiple form submits (#844)
  htdocs/js/self-service-password.js
Labels: enhancement

#842 remove useless show_policy function, now rendered by smarty template …
  lib/functions.inc.php
Labels: php

#856 Remove criteria depending on old password when unavailable (#855)
  htdocs/js/ppolicy.js
Labels: enhancement

#866 add docker image labels (#778) + update base image to php:8.2 + smarty to v4.4.1
  packaging/docker/Dockerfile
Labels: packaging

#847 Spec cleanup (#846)
  conf/config.inc.php
  htdocs/captcha.php
  htdocs/change.php
  htdocs/changesshkey.php
  htdocs/resetbyquestions.php
  htdocs/resetbytoken.php
  htdocs/sendsms.php
  htdocs/sendtoken.php
  htdocs/setattributes.php
  htdocs/setquestions.php
  lang/ar.inc.php
  lang/ca.inc.php
  lang/cn.inc.php
  lang/cs.inc.php
  lang/de.inc.php
  lang/ee.inc.php
  lang/el.inc.php
  lang/en.inc.php
  lang/es.inc.php
  lang/eu.inc.php
  lang/fr.inc.php
  lang/hu.inc.php
  lang/it.inc.php
  lang/ja.inc.php
  lang/nb-NO.inc.php
  lang/nl.inc.php
  lang/pl.inc.php
  lang/pt-BR.inc.php
  lang/pt-PT.inc.php
  lang/rs.inc.php
  lang/ru.inc.php
  lang/sk.inc.php
  lang/sl.inc.php
  lang/sv.inc.php
  lang/tr.inc.php
  lang/uk.inc.php
  lang/zh-CN.inc.php
  lang/zh-TW.inc.php
  lib/captcha.inc.php
  lib/functions.inc.php
  lib/smsapi-signal-cli.inc.php
  lib/smsapi-twilio.inc.php
  packaging/rpm/SPECS/self-service-password.spec
  scripts/encrypt_answers.php
Labels: packaging

#858 deb cleanup (#852)
  docs/config_general.rst
  docs/config_questions.rst
  docs/installation.rst
  docs/upgrade.rst
  packaging/README
  packaging/debian/changelog
  packaging/debian/compat
  packaging/debian/conffiles
  packaging/debian/control
  packaging/debian/copyright
  packaging/debian/replace_cache_dirs
  packaging/debian/rules
  packaging/debian/self-service-password.install
  packaging/debian/self-service-password.postinst
  packaging/debian/self-service-password.preinst
  tests/LangTest.php
Labels: packaging

#857 Avoid host header poisoning
  conf/config.inc.php
  docs/upgrade.rst
  htdocs/index.php
  htdocs/sendsms.php
  htdocs/sendtoken.php
  lang/ar.inc.php
  lang/ca.inc.php
  lang/cn.inc.php
  lang/cs.inc.php
  lang/de.inc.php
  lang/ee.inc.php
  lang/el.inc.php
  lang/en.inc.php
  lang/es.inc.php
  lang/eu.inc.php
  lang/fr.inc.php
  lang/hu.inc.php
  lang/it.inc.php
  lang/ja.inc.php
  lang/nb-NO.inc.php
  lang/nl.inc.php
  lang/pl.inc.php
  lang/pt-BR.inc.php
  lang/pt-PT.inc.php
  lang/rs.inc.php
  lang/ru.inc.php
  lang/sk.inc.php
  lang/sl.inc.php
  lang/sv.inc.php
  lang/tr.inc.php
  lang/uk.inc.php
  lang/zh-CN.inc.php
  lang/zh-TW.inc.php
  lib/functions.inc.php
Labels: security

#873 Use a dedicated CSS class for ppolicy div
  htdocs/js/ppolicy.js
  templates/policy.tpl
Labels: bug

#874 Test crypt_tokens parameter if SMS feature is enabled
  htdocs/index.php
  lang/ar.inc.php
  lang/ca.inc.php
  lang/cn.inc.php
  lang/cs.inc.php
  lang/de.inc.php
  lang/ee.inc.php
  lang/el.inc.php
  lang/en.inc.php
  lang/es.inc.php
  lang/eu.inc.php
  lang/fr.inc.php
  lang/hu.inc.php
  lang/it.inc.php
  lang/ja.inc.php
  lang/nb-NO.inc.php
  lang/nl.inc.php
  lang/pl.inc.php
  lang/pt-BR.inc.php
  lang/pt-PT.inc.php
  lang/rs.inc.php
  lang/ru.inc.php
  lang/sk.inc.php
  lang/sl.inc.php
  lang/sv.inc.php
  lang/tr.inc.php
  lang/uk.inc.php
  lang/zh-CN.inc.php
  lang/zh-TW.inc.php
  lib/functions.inc.php
Labels: enhancement
