Repository ltb-project/self-service-password, pull requests merged in 2024-02, with the labels that each got.

#833 Error handling when using the signal-cli api for sms
  lib/smsapi-signal-cli.inc.php
Labels: bug

#837 Upgrade Bootstrap to 5.3
  .gitignore
  composer.json
  composer.lock
  htdocs/css/self-service-password.css
  htdocs/vendor/bootstrap/css/bootstrap-theme.min.css
  htdocs/vendor/bootstrap/css/bootstrap-theme.min.css.map
  htdocs/vendor/bootstrap/css/bootstrap.min.css
  htdocs/vendor/bootstrap/css/bootstrap.min.css.map
  htdocs/vendor/bootstrap/fonts/glyphicons-halflings-regular.eot
  htdocs/vendor/bootstrap/fonts/glyphicons-halflings-regular.svg
  htdocs/vendor/bootstrap/fonts/glyphicons-halflings-regular.ttf
  htdocs/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff
  htdocs/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff2
  htdocs/vendor/bootstrap/js/bootstrap.min.js
  htdocs/vendor/bootstrap/js/jquery.selectunique.js
  templates/captcha.tpl
  templates/change.tpl
  templates/changesshkey.tpl
  templates/header.tpl
  templates/index.tpl
  templates/menu.tpl
  templates/policy.tpl
  templates/resetbyquestions.tpl
  templates/resetbytoken.tpl
  templates/sendsms.tpl
  templates/sendtoken.tpl
  templates/setattributes.tpl
  templates/setquestions.tpl
Labels: enhancement, dependencies

#841 Fix pt-BR translation for pwned password policy
  lang/pt-BR.inc.php
Labels: translation
