Repository ltb-project/self-service-password, pull requests merged in 2025-03, with the labels that each got.

#1052 Document how use env to configure LDAP TLS/SSL options
  docs/config_ldap.rst
  docs/installation.rst
Labels: documentation

#1056 Documenting fix for multi-tenant configuration
  docs/installation.rst
  packaging/docker/install
Labels: packaging, documentation

#1059 Fix CSS background
  htdocs/js/self-service-password.js
Labels: bug

#1061 Updated norwegian language
  lang/nb-NO.inc.php
Labels: translation
