Repository ltb-project/self-service-password, pull requests merged in 2025-01, with the labels that each got.

#1026 Fixing sms number truncate bug.
  htdocs/sendsms.php
  tests/sendsmsTest.php
Labels: bug

#1028 fix invalid token after captcha fail (#1018)
  htdocs/sendsms.php
  htdocs/sendtoken.php
Labels: bug

#1029 fix permission issue on config.inc.php link when container run unprivileged (#1022)
  packaging/docker/install
Labels: bug

#1034 update ltb-common to 0.5.0 (#1032)
  composer.json
Labels: enhancement

#1030 Fix input-group on sendtoken (mail) page
  templates/sendtoken.tpl
Labels: bug

#1037 Ukrainian translation corrected
  lang/uk.inc.php
Labels: translation

#1039 fix missing token after form fail (#1038)
  htdocs/sendtoken.php
Labels: bug
